/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as ApiPublicSebpayWebhookRouteImport } from './routes/api/public/sebpay/webhook'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSebpayWebhookRoute = ApiPublicSebpayWebhookRouteImport.update({
  id: '/api/public/sebpay/webhook',
  path: '/api/public/sebpay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/public/sebpay/webhook': typeof ApiPublicSebpayWebhookRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/public/sebpay/webhook': typeof ApiPublicSebpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/public/sebpay/webhook': typeof ApiPublicSebpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/checkout'
    | '/dashboard'
    | '/payment/failed'
    | '/payment/success'
    | '/api/public/sebpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/dashboard'
    | '/payment/failed'
    | '/payment/success'
    | '/api/public/sebpay/webhook'
  id:
    | '__root__'
    | '/checkout'
    | '/dashboard'
    | '/payment/failed'
    | '/payment/success'
    | '/api/public/sebpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiPublicSebpayWebhookRoute: typeof ApiPublicSebpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sebpay/webhook': {
      id: '/api/public/sebpay/webhook'
      path: '/api/public/sebpay/webhook'
      fullPath: '/api/public/sebpay/webhook'
      preLoaderRoute: typeof ApiPublicSebpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiPublicSebpayWebhookRoute: ApiPublicSebpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
